services:
  goalkicklive-db:
    image: postgres:15
    container_name: goalkicklive-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - goalkicklive_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: goalkicklive-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - goalkicklive-db

volumes:
  goalkicklive_data:
